apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: crypto-web
  template:
    metadata:
      labels:
        app: crypto-web
    spec:
      containers:
        - name: crypto-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
